// src/constants/testimonials.js
export const TESTIMONIALS = [
    {
      name: "John Doe",
      username: "@johndoe",
      userImage: "https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Notion",
      companyLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Notion-logo.svg/1024px-Notion-logo.svg.png",
      rating: 5,
      review: "Axion has been an absolute <highlight>game-changer</highlight> for our sales team. We've eliminated manual follow-ups and seen conversion rates improve by <highlight>60%</highlight> in just weeks!",
    },
    {
      name: "Jane Smith",
      username: "@janesmith",
      userImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      companyName: "Bubble",
      companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREj2v4-Xl-kNAOL06dAL27AkTnWTF8t7WXgQ&s",
      rating: 5,
      review: "Axion has <highlight>slashed our sales friction</highlight> completely. We're now able to handle enterprise clients with just a fraction of our previous headcount.",
    },
    {
      name: "Michael Johnson",
      username: "@michaeljohnson",
      userImage: "https://images.unsplash.com/photo-1508835277982-1c1b0e205603?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Zapier",
      companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZzbCDtUfNBcDbQ_rb_SL7xggScuVw4fJb4w&s",
      rating: 5,
      review: "Axion is truly <highlight>the future of sales</highlight>. Our team of 15 now handles what used to require 50+ people, with better results!",
    },
    {
      name: "Jason Matthew Carter",
      username: "@jasoncarter",
      userImage: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=2662&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Calendly",
      companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCrLgV-ZF_jRcG2wkXAaVnUmIi7KlcyzgOJg&s",
      rating: 4,
      review: "With Axion, our sales cycle went from weeks to <highlight>just days</highlight>. The AI handles all the tedious work while our team focuses on relationships.",
    },
    {
      name: "Robert Wilson",
      username: "@robertwilson",
      userImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Airtable",
      companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5HkuFtq_ojSDxyqdh3dsnFn1Q7qIpuiF6Xtw4dDnAPjrUv1066-8bswFYq0XDvYb5S-Q&usqp=CAU",
      rating: 5,
      review: "Axion has <highlight>transformed our enterprise sales</highlight>. Our team of 15 now accomplishes what previously required a department of 45.",
    },
    {
      name: "Jessica Martinez",
      username: "@jessicamartinez",
      userImage: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Figma",
      companyLogo: "https://cdn.sanity.io/images/599r6htc/regionalized/5094051dac77593d0f0978bdcbabaf79e5bb855c-1080x1080.png?w=540&h=540&q=75&fit=max&auto=format",
      rating: 5,
      review: "Axion is simply <highlight>magical</highlight>. It's like having an elite sales team that works 24/7 without breaks or burnout.",
    },
    {
      name: "David Lee",
      username: "@davidlee",
      userImage: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      companyName: "Smartsheet",
      companyLogo: "https://seekvectors.com/files/download/Smartsheet-02.jpg",
      rating: 4,
      review: "Our ROI with Axion has been <highlight>incredible</highlight>. We've cut costs by 60% while increasing our deal closure rate by 40%.",
    },
    {
      name: "Sarah Brown",
      username: "@sarahbrown",
      userImage: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      companyName: "Webflow",
      companyLogo: "https://cdn.prod.website-files.com/5f15081919fdf673994ab5fd/651f24a499bc8356ba844e0c_Webflow-Logo.svg",
      rating: 5,
      review: "I've never seen anything like Axion before. It's <highlight>completely revolutionized</highlight> how we approach sales at scale.",
    },
    {
      name: "James Taylor",
      username: "@jamestaylor",
      userImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
      companyName: "ClickUp",
      companyLogo: "https://1000logos.net/wp-content/uploads/2022/06/ClickUp-Emblem.png",
      rating: 5,
      review: "Axion has <highlight>supercharged our sales team</highlight>. We're closing deals 70% faster with only a third of our previous headcount.",
    },
    {
      name: "Laura White",
      username: "@laurawhite",
      userImage: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?q=80&w=3009&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      companyName: "Loom",
      companyLogo: "https://logowik.com/content/uploads/images/loom-icon7460.logowik.com.webp",
      rating: 4,
      review: "Our enterprise clients are <highlight>blown away</highlight> by Axion's capabilities. It feels like having an army of top-tier sales professionals at your fingertips.",
    }
  ];