import type { Metadata } from 'next';
import './globals.css';
import FooterSection from '@/components/footer';
import { Providers } from '@/components/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-serif antialiased">
    

        <Providers>
          {children}
        </Providers>

        <FooterSection />
      </body>
    </html>
  );
}
